# Production environment overrides
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  players:
    image: ghcr.io/jamiepinkham/players:main
    restart: unless-stopped
    networks:
      - default
      - web

  db:
    restart: unless-stopped

networks:
  web:
    external: true
