services:
  players:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ./rails:/app
      - ./rails/app/assets/builds:/app/app/assets/builds
      - ./docker/db/restore:/app/db/restore
    ports:
      - "3000:3000"
    depends_on:
      - db
      - assets
    env_file:
      - .env

  assets:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.assets
    volumes:
      - ./rails:/app
      - ./rails/app/assets/builds:/app/app/assets/builds
    env_file:
      - .env

  db:
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro

volumes:
  pgdata:
  assets:
