# QA environment overrides
# Use with: docker-compose -f docker-compose.yml -f docker-compose.qa.yml up

services:
  players:
    image: ghcr.io/jamiepinkham/players:main
    restart: unless-stopped
    ports:
      - "3000:3000"

  assets:
    image: ghcr.io/jamiepinkham/players:main
    restart: unless-stopped
    environment:
      WATCH: "0"

  db:
    restart: unless-stopped
