default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: postgres
  username: <%= ENV.fetch("POSTGRES_USER", "playersuser") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "playerspass") %>

development:
  <<: *default
  database: players_development

test:
  <<: *default
  database: players_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>