# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  host: localhost

development:
  <<: *default
  database: bmpl-development

test:
  <<: *default
  database: bmpl-test

production:
  <<: *default
  database: bmpl-finances
  username: <%= ENV.fetch("PROD_DB_USERNAME") %>
  password: <%= ENV.fetch("PROD_DB_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST") %>
  # For example, my host looks like this:
  # /cloudsql/vp-demo-383902:us-west1:vp-sql-instance
