# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e2f1a78516169538c291c12b1e585c7c80dc1781b588f2b8d3201569ddeeae61b79064764a39f701a78b16912ab826fa882bb0ca243083821bd0a24669b44f7

test:
  secret_key_base: 85cacd6e9a2982d340f12c85f6038953559179a532ec6703d42ac4246c2c174ac9e517e6e796033a95e90658f1e7cb1505bba0a31913a0a87e9360e65c3fd553


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
