source 'https://rubygems.org'
ruby "3.3.7"

gem 'dotenv-rails', '~> 3.2', groups: [:development, :test]

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 8.1.0'
# Use postgres as the database for Active Record
gem 'pg', '~> 1.6'
gem 'pg_search'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', '~> 13.0'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 4.2'
end

group :test do
  gem 'factory_bot_rails', '~> 6.5'
  gem 'faker', '~> 3.5'
  gem 'minitest'
end

# gem 'rails_12factor', group: :production  # Built into Rails 7

gem 'devise', '~> 5.0'
gem 'devise-jwt', '~> 0.13'
gem 'autoprefixer-rails', '~> 10.4'
gem 'httparty', '~> 0.24'
gem 'puma', '~> 7.0'
gem 'rack-timeout', '~> 0.7'
gem 'graphql', '~> 2.5'
gem 'graphiql-rails', '~> 1.10', group: :development
gem 'nokogiri', '~> 1.19'
gem 'solid_queue', '~> 1.1'

gem "foreman", "~> 0.90.0"
gem "net-smtp"
gem "net-pop"
gem "net-imap"
gem 'rails_admin', '~> 3.0'
gem 'rack-cors', '~> 3.0'

gem "jsbundling-rails", "~> 1.3"
gem "cssbundling-rails", "~> 1.4"
gem 'sassc-rails'

