source 'https://rubygems.org'
ruby "3.1.2"

gem 'dotenv-rails', groups: [:development, :test]

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1'
# Use postgres as the database for Active Record
gem 'pg'
gem 'pg_search'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

end

group :test do
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'minitest'
end

gem 'rails_12factor', group: :production

gem 'devise'
gem 'devise-jwt'
gem 'autoprefixer-rails'
gem 'httparty'
gem 'puma'
gem 'rack-timeout'
gem 'graphql'
gem 'graphiql-rails', group: :development
gem 'nokogiri'
gem 'dry-configurable', '0.12.1'
gem 'dry-container', '0.7.2'

gem "foreman", "~> 0.90.0"
gem "net-smtp"
gem "net-pop"
gem "net-imap"
gem 'rails_admin', '~> 3.0'
gem 'rack-cors'

gem "jsbundling-rails", "~> 1.3"
gem "cssbundling-rails", "~> 1.4"
gem 'sassc-rails'

